### ISSUE TITLE
Altitude control mode (AC)

### ISSUE THREAD

**Issue by pedsancue** [grvcTeam/Firmware#13]
**Objectives**

Introduce in the NUC Simulink scheme a position control limited to the altitude. The altitude level is supposed to be changed using the thrust RC channel, RC3. The modes will be switched using RC5. This mode is a previous step to have a control position mode, being the solutions found applicable to it.

**Nomenclature**

Simulink schemes are named as follows: _NUCControl_vX_Y_cZZZZZZZ_, being _X_ the control version, _Y_ the experimental version and _ZZZZZZZ_ the firmware commit this scheme is associated to.

**Comment by crdecos** [comment]
**Preliminary altitude hold experiments**

The solution including data recording, [NUCControl_v7_2_c66be4b6.zip](https://github.com/grvcTeam/Firmware/files/1561025/NUCControl_v7_2_c66be4b6.zip), has been tested, experiments _exp_7_NUCControl_v7_14_12_17_2_cuerda_ and _exp_8_NUCControl_v7_14_12_17_2_cuerda_ ,

**Comment by crdecos** [comment]
Modified solution to the altitude hold taking into account the problems experienced in previous experiments.
[NUCControl_v7_3_c66be4b6.zip](https://github.com/grvcTeam/Firmware/files/1561041/NUCControl_v7_3_c66be4b6.zip)
_To be tested soon._

**Comment by pedsancue** [comment]
New altitude control version. To be tested today.
[NUCControl_v7_4_c66be4b6.zip](https://github.com/grvcTeam/Firmware/files/1563160/NUCControl_v7_4_c66be4b6.zip)

**Comment by crdecos** [comment]
NUC control version including time_stamp recording.
[NUCControl_v7_5_c66be4b6.zip](https://github.com/grvcTeam/Firmware/files/1567802/NUCControl_v7_5_c66be4b6.zip)

**Comment by crdecos** [comment]
[NUCControl_v7_7_c66be4b6.zip](https://github.com/grvcTeam/Firmware/files/1575450/NUCControl_v7_7_c66be4b6.zip)

**Modifications:**
- Cascade altitude control included. Altitude PID reset from mode_total and Altitude_rates PID (corrected with the UAV attitude) from mode_hold
- The problem with RC5 0 being thrust mode solved
- Comments added to trace mode_total and mode_hold
