### ISSUE TITLE
Position control mode (PC)

### ISSUE THREAD

**Issue by pedsancue** [grvcTeam/Firmware#16]
**Objectives**

Introduce in the NUC Simulink scheme a position control. The altitude level is changed using the thrust RC channel, RC3, and the local position with the pitch and roll channels, RC1 and RC2. The modes will be switched using RC5. 

**Nomenclature**

Simulink schemes are named as follows: _NUCControl_vX_Y_cZZZZZZZ_, being _X_ the control version, _Y_ the experimental version and _ZZZZZZZ_ the firmware commit this scheme is associated to.

**Comment by crdecos** [comment]
[NUCControl_v8_2_c45b232b.zip](https://github.com/grvcTeam/Firmware/files/1601376/NUCControl_v8_2_c45b232b.zip)

**Modifications:**
- A

**Comment by crdecos** [comment]
After several weeks of intense work, the final versions for the basic controller are the following:
[NUCControl_v8_4_c45b232b.zip](https://github.com/grvcTeam/Firmware/files/1715570/NUCControl_v8_4_c45b232b.zip) (Speed)
[NUCControl_v8_5_c45b232b.zip](https://github.com/grvcTeam/Firmware/files/1715571/NUCControl_v8_5_c45b232b.zip) (Position)
